# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'hotMaps' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'GoogleMaps'
	pod 'GooglePlaces'	
	pod 'SwiftSocket'

  # Pods for hotMaps

  target 'hotMapsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hotMapsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
